#!/bin/sh
# 设置 LAN IP
uci set network.lan.ipaddr='192.168.7.1'
uci set network.lan.gateway='192.168.7.254' # 假设你的主路由是 7.254，请按实际修改
uci set network.lan.dns='192.168.7.254'

# 开启旁路由防火墙伪装和转发
uci set firewall.@zone[0].forward='ACCEPT'
uci set firewall.@zone[0].masq='1'

# 禁用 DHCP 服务器，避免跟主路由冲突
uci set dhcp.lan.ignore='1'

uci commit network
uci commit firewall
uci commit dhcp
exit 0
